# Generated by Django 3.1.2 on 2020-10-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201023_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
